- name: Copy build script local to remote machine
   hosts: remote_machine
   tasks:
    - name: Copy script to remote_machine
      template: src=build.sh dest=~/script.sh mode=755
    - name: Execute script on remote_machine
      script: sh ~/script.sh
