# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: centos gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: ansible check with centos:latest
      # replace "master" with any valid ref
      uses: roles-ansible/check-ansible-centos-latest-action@master
      with:
        add: build.sh /
        entrypoint: "bash /build.sh"
      
